# Generated by Django 5.2.4 on 2025-07-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cin',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
