# Generated by Django 5.2.4 on 2025-07-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
