# Generated by Django 5.2.4 on 2025-08-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
