# Generated by Django 5.2.4 on 2025-08-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content_subtitle_file'),
        ('courses', '0002_delete_quiz'),
    ]

    operations = [
    ]
