# Generated by Django 5.2.4 on 2025-08-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_content_image_alt_text"),
        ("courses", "0003_merge_0002_content_subtitle_file_0002_delete_quiz"),
    ]

    operations = []
