# Generated by Django 5.2.4 on 2025-07-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_answer_text_alter_question_difficulty_level_and_more"),
        ("quiz", "0002_quizsubmission_submissionanswer"),
    ]

    operations = []
